/// Web Application Firewall (WAF) detection engine.
///
/// Identifies WAF products by matching response headers, cookies,
/// and body content against known signatures for Cloudflare, AWS WAF,
/// ModSecurity, Sucuri, Akamai, and others.
use crate::models::WafInfo;
use reqwest::header::HeaderMap;

/// A WAF signature definition with header, cookie, and body checks.
struct WafSig {
    name: &'static str,
    manufacturer: &'static str,
    header_checks: &'static [(&'static str, &'static str)],
    cookie_checks: &'static [&'static str],
    body_checks: &'static [&'static str],
}

/// Known WAF signature database.
const WAF_SIGS: &[WafSig] = &[
    WafSig {
        name: "Cloudflare",
        manufacturer: "Cloudflare Inc.",
        header_checks: &[("server", "cloudflare"), ("cf-ray", ""), ("cf-cache-status", "")],
        cookie_checks: &["__cfduid", "__cf_bm", "cf_clearance"],
        body_checks: &["cloudflare-nginx", "cf-error-page"],
    },
    WafSig {
        name: "AWS WAF",
        manufacturer: "Amazon Web Services",
        header_checks: &[("x-amz-cf-id", ""), ("x-amz-cf-pop", ""), ("x-amzn-", ""), ("server", "cloudfront")],
        cookie_checks: &["aws-waf-token", "aws-alb"],
        body_checks: &["Request blocked", "challenge-form", "aws.waf"]
    },
    WafSig {
        name: "ModSecurity",
        manufacturer: "Trustwave",
        header_checks: &[("x-modsecurity", ""), ("x-powered-by", "mod_security"), ("x-robots-tag", "noindex")],
        cookie_checks: &[],
        body_checks: &["mod_security", "ModSecurity", "This error was generated by ModSecurity"],

    },
    WafSig {
        name: "Sucuri",
        manufacturer: "Sucuri / GoDaddy",
        header_checks: &[("x-sucuri-id", ""), ("x-sucuri-cache", ""), ("x-sucuri-block", "")],
        cookie_checks: &["sucuri_cloudproxy"],
        body_checks: &["sucuri.net", "Sucuri WebSite Firewall", "cloudproxy.sucuri.net"]
    },
    WafSig {
        name: "Akamai",
        manufacturer: "Akamai Technologies",
        header_checks: &[("server", "akamai"), ("x-akamai-", ""), ("x-akamai-transformed", "")],
        cookie_checks: &["ak_bmsc", "bm_sz", "akavpau"],
        body_checks: &["akamai", "AkamaiGHost"]
    },
    WafSig {
        name: "Fastly",
        manufacturer: "Fastly Inc.",
        header_checks: &[("x-fastly-request-id", ""), ("x-served-by", "cache-"), ("x-cache", ""), ("x-timer", "")],
        cookie_checks: &[],
        body_checks: &[]
    },
    WafSig {
        name: "Imperva Incapsula",
        manufacturer: "Imperva",
        header_checks: &[("x-cdn", "incapsula"), ("x-iinfo", ""), ("x-request-id", "")],
        cookie_checks: &["incap_ses", "visid_incap", "nlbi_"],
        body_checks: &["Incapsula", "_Incapsula_Resource", "incapsula.com"]
    },
    WafSig {
        name: "StackPath",
        manufacturer: "StackPath",
        header_checks: &[("server", "stackpath"), ("x-mattr", ""), ("x-served-by", "stackpath")],
        cookie_checks: &[],
        body_checks: &[]
    },
    WafSig {
        name: "Barracuda",
        manufacturer: "Barracuda Networks",
        header_checks: &[("x-requested-with", ""), ("x-powered-by", "barracuda")],
        cookie_checks: &["barra_counter_session"],
        body_checks: &["Barracuda", "barracuda.net"],

    },
    WafSig {
        name: "F5 BIG-IP ASM",
        manufacturer: "F5 Networks",
        header_checks: &[("server", "big-ip"), ("x-application-context", ""), ("x-f5-", "")],
        cookie_checks: &["TS", "BIGipServer", "F5_"],
        body_checks: &["The requested URL was rejected", "F5 Networks", "support.f5.com"]
    },
    WafSig {
        name: "Wordfence",
        manufacturer: "Defiant Inc.",
        header_checks: &[],
        cookie_checks: &["wfvt_", "wordfence_"],
        body_checks: &["Wordfence", "Generated by Wordfence"],

    },
    WafSig {
        name: "Comodo cWatch",
        manufacturer: "Comodo",
        header_checks: &[("server", "cwatch"), ("x-cwatch", "")],
        cookie_checks: &[],
        body_checks: &["cWatch", "comodo"]
    },
    WafSig {
        name: "Azure Application Gateway",
        manufacturer: "Microsoft",
        header_checks: &[("server", "azure"), ("x-azure-", ""), ("x-powered-by", "azure")],
        cookie_checks: &["AzureAppGW"],
        body_checks: &["azure", "Application Gateway"]
    },
    WafSig {
        name: "Radware",
        manufacturer: "Radware",
        header_checks: &[("server", "radware"), ("x-radware", ""), ("x-request-uid", "")],
        cookie_checks: &["radware", "alt_uid"],
        body_checks: &["Radware", "AppWall"]
    },
    WafSig {
        name: "Airlock",
        manufacturer: "Ergon",
        header_checks: &[("x-airlock-", "")],
        cookie_checks: &["AL_", "airlock"],
        body_checks: &["Airlock", "ergon"]
    },
    WafSig {
        name: "Citrix NetScaler",
        manufacturer: "Citrix",
        header_checks: &[("server", "netscaler"), ("x-netscaler", ""), ("via", "netscaler")],
        cookie_checks: &["NSC_", "citrix_ns"],
        body_checks: &["NetScaler", "NS-CACHE"]
    },
];

/// Detect WAF presence by analyzing response headers, body, and cookies.
///
/// Returns `Some(WafInfo)` if a WAF is detected, `None` otherwise.
pub fn detect(headers: &HeaderMap, body: &str, cookies: &[crate::models::CookieInfo]) -> Option<WafInfo> {
    let body_lower = body.to_lowercase();

    // Loop: check each WAF signature
    for sig in WAF_SIGS {
        let mut found_signals: Vec<String> = Vec::new();
        let mut categories: std::collections::HashSet<&str> = std::collections::HashSet::new();

        // Step: check response headers for WAF indicators
        for (hdr, pat) in sig.header_checks {
            if let Some(val) = headers.get(*hdr) {
                if let Ok(v) = val.to_str() {
                    let v_lower = v.to_lowercase();
                    if pat.is_empty() || v_lower.contains(pat) {
                        found_signals.push(format!("header {}: {}", hdr, v));
                        categories.insert("header");
                    }
                }
            }
        }

        // Step: check cookie names for WAF indicators
        for cp in sig.cookie_checks {
            for c in cookies {
                if c.name.to_lowercase().contains(&cp.to_lowercase()) {
                    found_signals.push(format!("cookie {}", c.name));
                    categories.insert("cookie");
                }
            }
        }

        // Step: check body content for WAF indicators
        for bp in sig.body_checks {
            if body_lower.contains(&bp.to_lowercase()) {
                found_signals.push(format!("body contains '{}'", bp));
                categories.insert("body");
            }
        }

        // Check: require at least 2 categories, or 1 category with 2+ signals
        if categories.len() >= 2 || (categories.len() == 1 && found_signals.len() >= 2) {
            return Some(WafInfo {
                detected: true,
                name: sig.name.to_string(),
                manufacturer: sig.manufacturer.to_string(),
                signals: found_signals,
            });
        }
    }

    None
}
